name: "vault_flow"
version: "1.0.0"
profile: "VaultFlow"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  vault_flow:
    staging:
      +materialized: view
    marts:
      +materialized: table
